---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: git-revisionist-historian

run:
  path: sh
  args:
  - -c
  - |
    cd git-revisionist-historian && ./gradlew clean build --info --stacktrace
