---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: "8"

inputs:
- name: grh

run:
  path: bash
  args:
  - -exc
  - |
    cd grh && ./gradlew build publishGrhPublicationToConcourseArtifactRepository
