---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: git-revisionist-historian

run:
  path: bash
  args:
  - -exc
  - |
    git-revisionist-historian/gradlew build publishGrhPublicationToConcourseArtifactRepository -p git-revisionist-historian
