---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: "8"

inputs:
- name: grh

outputs:
- name: .m2

caches:
- path: .gradle
- path: tmp
- path: .m2
- path: grh/.gradle

run:
  path: bash
  args:
  - -exc
  - |
    export JAVA_TOOL_OPTIONS="-Dgradle.user.home=$(pwd)/.gradle -Dmaven.repo.local=$(pwd)/.m2 -Djava.io.tmpdir=$(pwd)/tmp"
    cd grh
    ./gradlew -Dorg.gradle.daemon=false build publishToMavenLocal
