---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: "8"

inputs:
- name: grh
- name: .m2

caches:
- path: .gradle
- path: tmp
- path: .m2
- path: grh/.gradle

# NOTE: This approach is a temporary insecure hack, because the concourse task instance
#       does not have git credentials (they only exist on the resource instance)
# See https://serverfault.com/a/701637/392067
# Also note we do not use set bash -x option, otherwise we'd print the key in the log

# It doesn't actually assert anything other than a zero return code.
# There is an acceptance test which can run locally and does solutions.
# This will eventually become a better solution, and just create a local/remote pair of
# git repos on the fly, to avoid all the permissions issues. Then it can
# be added as part of build.yml like the API acceptance test already is.
# See test/acceptance/grh/cli/CliProcessorAcceptanceTest.kt:11
# and  https://www.pivotaltracker.com/story/show/151149103
run:
  path: bash
  args:
  - -ec
  - |
    mkdir -p ~/.ssh
    ssh-keyscan -H github.com >> ~/.ssh/known_hosts # NOT SECURE, VULNERABLE TO MITM
    echo "${GIT_REVISIONIST_HISTORIAN_TEST_REPO_WRITEABLE_DEPLOY_KEY}" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    git clone git@github.com:thewoolleyman/git-revisionist-historian-test-repo.git
    export JAVA_TOOL_OPTIONS="-Dgradle.user.home=$(pwd)/.gradle -Dmaven.repo.local=$(pwd)/.m2 -Djava.io.tmpdir=$(pwd)/tmp"
    cd git-revisionist-historian-test-repo
    java -jar ../.m2/com/thewoolleyweb/grh/git-revisionist-historian/dev/git-revisionist-historian-dev.jar --processor cli
