---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: grh
- name: version

run:
  path: bash
  args:
  - -exc
  - |
    cd grh && ./gradlew publishGrhPublicationToGrhRepository
