---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: "8"

inputs:
- name: grh
- name: version

caches:
- path: .gradle
- path: tmp
- path: .m2
- path: grh/.gradle

run:
  path: bash
  args:
  - -exc
  - |
    export JAVA_TOOL_OPTIONS="-Dgradle.user.home=$(pwd)/.gradle -Dmaven.repo.local=$(pwd)/.m2 -Djava.io.tmpdir=$(pwd)/tmp"
    export VERSION_FILE_PATH=$(pwd)/version/version
    cd grh
    ./gradlew -Dorg.gradle.daemon=false publishGrhPublicationToGrhRepository
