---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: "8"

inputs:
- name: grh
- name: git-revisionist-historian-test-repo

run:
  path: bash
  args:
  - -exc
  - |
    curl -O https://s3.amazonaws.com/git-revisionist-historian/com/thewoolleyweb/grh/git-revisionist-historian/dev/git-revisionist-historian-dev.jar
    java -jar git-revisionist-historian-dev.jar --config https://raw.githubusercontent.com/thewoolleyman/git-revisionist-historian-test-repo/master/grh-config.json --repo thewoolleyman/git-revisionist-historian-test-repo --processor api
