###############################################################################
##############################                   ##############################
##############################     RESOURCES     ##############################
##############################                   ##############################
###############################################################################

resources:

##############################     GIT RESOURCES     ##############################

  - name: git-revisionist-historian
    type: git
    source:
#      uri: git@github.com:thewoolleyman/git-revisionist-historian.git
      uri: https://github.com/thewoolleyman/git-revisionist-historian.git
      branch: master

###############################################################################
##############################                   ##############################
##############################       JOBS        ##############################
##############################                   ##############################
###############################################################################

jobs:
  - name: build
    plan:
      - get: git-revisionist-historian
        trigger: true
      - task: build
        file: git-revisionist-historian/ci/tasks/build.yml
