###############################################################################
##############################                   ##############################
##############################     RESOURCES     ##############################
##############################                   ##############################
###############################################################################

resources:

##############################   GIT RESOURCES   ##############################

  - name: grh
    type: git
    source:
      uri: https://github.com/thewoolleyman/git-revisionist-historian.git
      branch: master # change to test with a branch

  - name: grh-test-repo
    type: git
    source:
      uri: https://github.com/thewoolleyman/git-revisionist-historian-test-repo.git
      branch: master

############################## SEMVER RESOURCES  ##############################

  - name: version
    type: semver
    source:
      driver: s3
      initial_version: 0.0.1
      bucket: git-revisionist-historian
      key: version
      access_key_id: {{AWS_ACCESS_KEY_ID}}
      secret_access_key: {{AWS_SECRET_ACCESS_KEY}}

###############################################################################
##############################                   ##############################
##############################       JOBS        ##############################
##############################                   ##############################
###############################################################################

jobs:
  - name: build
    plan:
      - get: grh
        trigger: true
      - task: build
        file: grh/ci/tasks/build.yml

  - name: publish-dev
    plan:
      - get: grh
        trigger: true
        passed: [build]
      - get: version # not used, but required in order to use same publish.yml task which has it as an input
      - task: publish
        file: grh/ci/tasks/publish.yml
        params:
          DEV_VERSION: dev # change to test with a branch
          AWS_ACCESS_KEY_ID: {{AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: {{AWS_SECRET_ACCESS_KEY}}

  - name: run-cli-processor-on-test-repo
    plan:
      - get: grh
        passed: [publish-dev]
        trigger: true
      - task: run-cli-processor-on-test-repo
        file: grh/ci/tasks/run-cli-processor-on-test-repo.yml
        params:
          DEV_VERSION: dev # change to test with a branch
          GIT_REVISIONIST_HISTORIAN_TEST_REPO_WRITEABLE_DEPLOY_KEY: {{GIT_REVISIONIST_HISTORIAN_TEST_REPO_WRITEABLE_DEPLOY_KEY}}

  - name: run-api-processor-on-test-repo
    plan:
      - get: grh
        passed: [run-cli-processor-on-test-repo]
        trigger: true
      - get: grh-test-repo
        trigger: true
      - task: run-api-processor-on-test-repo
        file: grh/ci/tasks/run-api-processor-on-test-repo.yml
        params:
          DEV_VERSION: dev # change to test with a branch
          GITHUB_PERSONAL_ACCESS_TOKEN: {{GIT_REVISIONIST_HISTORIAN_TEST_REPO_PERSONAL_ACCESS_TOKEN}} # https://github.com/settings/tokens

  - name: publish-alpha
    plan:
      - get: grh
        passed: [run-api-processor-on-test-repo]
      - get: version
        params: {pre: rc}
      - task: publish
        file: grh/ci/tasks/publish.yml
        params:
          VERSION_FILE_PATH: ../version/version
          AWS_ACCESS_KEY_ID: {{AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: {{AWS_SECRET_ACCESS_KEY}}
      - put: version
        params: {file: version/version}

  - name: publish-final
    plan:
      - get: grh
        passed: [publish-alpha]
      - get: version
        params: {bump: final}
      - task: publish
        file: grh/ci/tasks/publish.yml
        params:
          VERSION_FILE_PATH: ../version/version
          AWS_ACCESS_KEY_ID: {{AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: {{AWS_SECRET_ACCESS_KEY}}
      - put: version
        params: {file: version/version}

  - name: bump-major
    plan:
      - put: version
        params: {bump: major}

  - name: bump-minor
    plan:
      - put: version
        params: {bump: minor}

  - name: bump-patch
    plan:
      - put: version
        params: {bump: patch}
