###############################################################################
##############################                   ##############################
##############################     RESOURCES     ##############################
##############################                   ##############################
###############################################################################

resources:

##############################   GIT RESOURCES   ##############################

  - name: grh
    type: git
    source:
      uri: https://github.com/thewoolleyman/git-revisionist-historian.git
      branch: master # change to test with a branch

############################## SEMVER RESOURCES  ##############################

  - name: version
    type: semver
    source:
      driver: s3
      initial_version: 0.0.1
      bucket: git-revisionist-historian
      key: version
      access_key_id: {{AWS_ACCESS_KEY_ID}}
      secret_access_key: {{AWS_SECRET_ACCESS_KEY}}

###############################################################################
##############################                   ##############################
##############################       JOBS        ##############################
##############################                   ##############################
###############################################################################

jobs:
  - name: build
    plan:
      - get: grh
        trigger: true
      - task: build
        file: grh/ci/tasks/build.yml
        params:
          GITHUB_PERSONAL_ACCESS_TOKEN: {{GITHUB_PERSONAL_ACCESS_TOKEN}} # https://github.com/settings/tokens
      - task: cli-processor-acceptance-test
        file: grh/ci/tasks/cli-processor-acceptance-test.yml
        params:
          GIT_REVISIONIST_HISTORIAN_TEST_REPO_WRITEABLE_DEPLOY_KEY: {{GIT_REVISIONIST_HISTORIAN_TEST_REPO_WRITEABLE_DEPLOY_KEY}}
      - task: publish-dev
        file: grh/ci/tasks/publish.yml
        params:
          AWS_ACCESS_KEY_ID: {{AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: {{AWS_SECRET_ACCESS_KEY}}

  - name: run-published-jar-with-cli
    plan:
      - get: grh
        passed: [build]
        trigger: true
      - task: run-published-jar-with-cli
        file: grh/ci/tasks/run-published-jar-with-cli.yml
        params:
          GIT_REVISIONIST_HISTORIAN_TEST_REPO_WRITEABLE_DEPLOY_KEY: {{GIT_REVISIONIST_HISTORIAN_TEST_REPO_WRITEABLE_DEPLOY_KEY}}

  - name: run-published-jar-with-api
    plan:
      - get: grh
        passed: [run-published-jar-with-cli]
        trigger: true
      - task: run-published-jar-with-api
        file: grh/ci/tasks/run-published-jar-with-api.yml
        params:
          GITHUB_PERSONAL_ACCESS_TOKEN: {{GITHUB_PERSONAL_ACCESS_TOKEN}} # https://github.com/settings/tokens

  - name: publish-alpha
    plan:
      - get: grh
        passed: [run-published-jar-with-api]
      - get: version
        params: {pre: rc}
      - task: publish
        file: grh/ci/tasks/publish.yml
        params:
          AWS_ACCESS_KEY_ID: {{AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: {{AWS_SECRET_ACCESS_KEY}}
      - put: version
        params: {file: version/version}

  - name: publish-final
    plan:
      - get: grh
        passed: [publish-alpha]
      - get: version
        params: {bump: final}
      - task: publish
        file: grh/ci/tasks/publish.yml
        params:
          AWS_ACCESS_KEY_ID: {{AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: {{AWS_SECRET_ACCESS_KEY}}
      - put: version
        params: {file: version/version}

  - name: bump-major
    plan:
      - put: version
        params: {bump: major}

  - name: bump-minor
    plan:
      - put: version
        params: {bump: minor}

  - name: bump-patch
    plan:
      - put: version
        params: {bump: patch}
